# name: pre-commit
# 
# on:
#   pull_request:
# 
# jobs:
#   common:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3
# 
#       - name: pre-commit
#         uses: ./.github/actions/pre-commit
#         with:
#           check-type: common
# 
#   terraform:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3
# 
#       - name: pre-commit
#         uses: ./.github/actions/pre-commit
#         with:
#           check-type: terraform
# 
#   golang:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3
# 
#       - name: pre-commit
#         uses: ./.github/actions/pre-commit
#         with:
#           check-type: golang
# 
#   renovate:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3
# 
#       - name: pre-commit
#         uses: ./.github/actions/pre-commit
#         with:
#           check-type: renovate

permissions:
  id-token: write
  contents: read

name: Scan Terraform
on:
  push:

jobs:
  scan-terraform:
    uses: defenseunicorns/uds-common-workflows/.github/workflows/terraform-scan.yaml@fix-scan-init
    secrets: inherit
    with:
      soft-fail: true
      github-token: $GITHUB_TOKEN

